BEGIN;

DROP TABLE IF EXISTS user CASCADE; 

CREATE TABLE user (
id SERIAL PRIMARY KEY ,
username VARCHAR(100) NOT NULL ,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL 
);

COMMIT;
